/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PackageMg } from "./PackageMg";
export * as factories from "./factories";
export { PackageMg__factory } from "./factories/PackageMg__factory";
